FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ARG BIN_PATH=dist/linux-x64/pocketbase_mcp
COPY ${BIN_PATH} /usr/local/bin/pocketbase_mcp
RUN chmod +x /usr/local/bin/pocketbase_mcp

ENTRYPOINT ["/usr/local/bin/pocketbase_mcp"]
